// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZ9nXFkinOQXXBcYs6rxJtz6qLrwqTYM',
    appId: '1:633982428847:web:27fa50e8b59aad07cb965a',
    messagingSenderId: '633982428847',
    projectId: 'e-commerce-114ba',
    authDomain: 'e-commerce-114ba.firebaseapp.com',
    storageBucket: 'e-commerce-114ba.appspot.com',
    measurementId: 'G-7Q04JC16RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrU-WzBU14moUV2Tv2ZBcDyYNciMFOPRw',
    appId: '1:633982428847:android:ba0c85e8b68dac22cb965a',
    messagingSenderId: '633982428847',
    projectId: 'e-commerce-114ba',
    storageBucket: 'e-commerce-114ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfd0wQZ-k2zP6pUMV4STLzkANn3YV4ZVk',
    appId: '1:633982428847:ios:8fa8c3852207c207cb965a',
    messagingSenderId: '633982428847',
    projectId: 'e-commerce-114ba',
    storageBucket: 'e-commerce-114ba.appspot.com',
    androidClientId: '633982428847-3endg6kv8k4td00o08840hllubq4fa0u.apps.googleusercontent.com',
    iosClientId: '633982428847-oo7n0oa300bkmpp2e0b2jhfubkju8pnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqZ9nXFkinOQXXBcYs6rxJtz6qLrwqTYM',
    appId: '1:633982428847:web:a1de834dc6298882cb965a',
    messagingSenderId: '633982428847',
    projectId: 'e-commerce-114ba',
    authDomain: 'e-commerce-114ba.firebaseapp.com',
    storageBucket: 'e-commerce-114ba.appspot.com',
    measurementId: 'G-XBDJ4ZF15F',
  );

}